name: Manter Supabase Ativo
on:
  schedule:
    - cron: '0 0 * * 1,4' # Roda segunda e quinta às 00:00
  workflow_dispatch: # Ativa o botão manual

jobs:
  ping_supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Enviando Ping para o Banco de Dados
        run: |
          curl -i -X GET "https://kidpprfegedkjifbwkju.supabase.co/rest/v1/Permissoes?select=*" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"